package dsa_project_nb;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ttrun
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Close_ = new javax.swing.JLabel();
        button_GWG = new javax.swing.JButton();
        button_SG = new javax.swing.JButton();
        label_Welcome = new javax.swing.JLabel();
        label_blabla = new javax.swing.JLabel();
        buttonBigSmall = new javax.swing.JButton();
        buttonOther = new javax.swing.JButton();

        jLabel_Close_.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel_Close_.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_Close_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Close_.setText("X");
        jLabel_Close_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Close_MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        button_GWG.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        button_GWG.setText("Guess Words Game");
        button_GWG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_GWGActionPerformed(evt);
            }
        });

        button_SG.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        button_SG.setText("Squid Game");
        button_SG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_SGActionPerformed(evt);
            }
        });

        label_Welcome.setFont(new java.awt.Font("Verdana", 0, 48)); // NOI18N
        label_Welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Welcome.setText("Welcome !");

        label_blabla.setBackground(new java.awt.Color(0, 0, 0));
        label_blabla.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        label_blabla.setForeground(new java.awt.Color(102, 102, 0));
        label_blabla.setBackground(new java.awt.Color(234, 234, 234));
        label_blabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_blabla.setText("Choose the game you want to play");

        buttonBigSmall.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        buttonBigSmall.setText("Big or Small ?");
        buttonBigSmall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBigSmallActionPerformed(evt);
            }
        });

        buttonOther.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        buttonOther.setText("Others");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(label_Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_blabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(button_SG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_GWG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonBigSmall, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(buttonOther, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(label_Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(label_blabla, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_GWG, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBigSmall, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonOther, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_SG, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_Close_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Close_MouseClicked

        System.exit(0);
    }//GEN-LAST:event_jLabel_Close_MouseClicked

    private void button_GWGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_GWGActionPerformed
        // TODO add your handling code here:
        Guess_Word_Game gwg = new Guess_Word_Game();
    gwg.setVisible(true);
    this.dispose(); // Close the homepage
    }//GEN-LAST:event_button_GWGActionPerformed

    private void button_SGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_SGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_SGActionPerformed

    private void buttonBigSmallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBigSmallActionPerformed
        // TODO add your handling code here:                                               
    // Open the Big or Small game when the button is clicked
    BigOrSmall bosg = new BigOrSmall();
    bosg.setVisible(true);  // Show the new game window
    this.dispose();  // Close the current homepage window

    }//GEN-LAST:event_buttonBigSmallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBigSmall;
    private javax.swing.JButton buttonOther;
    private javax.swing.JButton button_GWG;
    private javax.swing.JButton button_SG;
    private javax.swing.JLabel jLabel_Close_;
    private javax.swing.JLabel label_Welcome;
    private javax.swing.JLabel label_blabla;
    // End of variables declaration//GEN-END:variables
}
